default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: 120.46.3.97
  port: 3306
  database: h_db22373362
  username: u22373362
  password: Aa404254

test:
  <<: *default
  host: 120.46.3.97
  port: 3306
  database: h_db22373362
  username: u22373362
  password: Aa404254

production:
  <<: *default
  host: 120.46.3.97
  port: 3306
  database: h_db22373362
  username: u22373362
  password: Aa404254